#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "$(tput setaf 1)Illegal number of parameters! Usage: $(tput setaf 3)$ ./program.sh [project-directory] [device-serial-number]$(tput setaf 7)"
    exit
fi

if [ ! -f "$1/main.c" ]; then
    echo "The specified project's entry point (/main.c) could not be found!"
    exit
fi

cd $1

if [ -d "build" ]; then
    echo && echo "$(tput setaf 1)Removing old ./build directory...$(tput setaf 7)"
    rm -r build/
fi
mkdir build && cd build

echo "$(tput setaf 3)Compiling..."
avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o main.o ../main.c

echo "$(tput setaf 4)Linking binary to ATmega328P libraries..."
avr-gcc -mmcu=atmega328p main.o -o main

echo "$(tput setaf 5)Converting linked binaries to hexadecimal for EEPROM..."
avr-objcopy -O ihex -R .eeprom main main.hex

echo "$(tput setaf 6)Flashing microcontroller...$(tput setaf 7)"
avrdude -F -V -c arduino -p ATMEGA328P -P /dev/cu.usbmodem$2 -b 115200 -U flash:w:main.hex

echo "$(tput setaf 5)Process completed!$(tput setaf 7)" && echo